# Generated by Django 4.1.7 on 2023-04-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileid',
            name='title',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
